channels:
  targets:
  - [viscid-hub, main]

travis:
  secure:
    BINSTAR_TOKEN: eAuPsDbWgsL6HJKEckl3lSoT4ZGzAC0quUALFcRkAwdYXa1k6DfgLgqy/ygT1XQ1+qLZhJqX9EzLYcWfkOZe5d6+h9WvglKq4ktac9yQ6myvNdEGXwM9Z3qjrqBkCAridXDbIdlkNOq/EB2xgQDguz43LAemfltKJGbGvdcV2H+jMbuQs+zyuKQhk4ccvmPAusGzWHInlXZNm9pV4K78BM+ap8aTKHM856dgH/flGBTje3IWgDg0nJtjt1F8tjJFUEXYy3chQVaVsc8VmnkjTBcfFX9n1noHkpExNsCt+dhbbmaSkX7xpmQZZ6KULbunMhXe4X2GXDoH6+IXACW73gGM9Ym2r5oHXWDLIkhuVZiPugp9uxGikOA4ckr6pKwHFCOWhKwUVzg0/eSm7zTfl4e10jQR8Y+og9c8UyVzMt0KqlzBHMGYbnhdqwNIgz8HU52dtSBCDfFLZgo7wPKS9tMjS9Z164jCrzQk4ykS7XgLftKYbPvMTbQHNyG+miqkhECZhm+CZ6tnL5WhoOMk26s6CGxD5zEqFxoz1zEeyzbeL/C4YNPYIk5wB9rl5o1VEs6zuxUOV1ybf4I+bylVSRwUIl3wjb7PXC6FUy8zXpK66ovUAALqtXdGXrmLc/TI4BvJyD/vo6RPZYwVI9QoQqcxgeNPChoqDAJLMSjHFq0=
appveyor:
  secure:
    BINSTAR_TOKEN: 9O82YEDOL2SqS1j6GkDUQSmIVgF8OhykUw5LfD9c6zZgHfswA6L3Kfmup+h/JcAB
